/* 
*To change this license header, choose License Headers in Project Properties.
 *To change this template file, choose Tools | Templates
 *and open the template in the editor.
 */ 
package networkanomalydetection; 
import com.birosoft.liquid.LiquidLookAndFeel; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
 
 
23 
 
/** 
 * 
 * @author THILIPAN 
 */ 
public class Login extends javax.swing.JFrame { 
 
    /** 
     * Creates new form Login 
     */ 
    public Login() { 
        initComponents(); 
    } 
    /** 
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always 
     * regenerated by the Form Editor. 
     */ 
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN
BEGIN:initComponents 
    private void initComponents() { 
 
        jLabel4 = new javax.swing.JLabel(); 
 
 
24 
 
        jTextField1 = new javax.swing.JTextField(); 
        jLabel8 = new javax.swing.JLabel(); 
        jLabel9 = new javax.swing.JLabel(); 
        jButton3 = new javax.swing.JButton(); 
        jLabel1 = new javax.swing.JLabel(); 
        jPasswordField1 = new javax.swing.JPasswordField(); 
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
        setTitle("Login"); 
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout()); 
 
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N 
        jLabel4.setText("LOGIN"); 
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 
110, 30)); 
 
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N 
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 
100, 170, 30)); 
 
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jLabel8.setText("ENTER USERNAME : "); 
 
 
25 
 
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 
110, 180, -1)); 
 
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jLabel9.setText("ENTER PASSWORD : "); 
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 
180, 180, -1)); 
 
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton3.setText("LOGIN"); 
        jButton3.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton3ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 
250, 210, 40)); 
 
        jLabel1.setText("        "); 
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 320)); 
 
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N 
 
 
26 
 
        getContentPane().add(jPasswordField1, new 
org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, 30)); 
 
        pack(); 
    }// </editor-fold>//GEN-END:initComponents 
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton3ActionPerformed 
        // TODO add your handling code here: 
        try { 
            LiquidLookAndFeel.setLiquidDecorations(true, "mac"); 
            //LiquidLookAndFeel.setStipples(false); 
            LiquidLookAndFeel.setPanelTransparency(true); 
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel"); 
            java.awt.EventQueue.invokeLater(new Runnable() { 
                public void run() { 
               String username= jTextField1.getText(); 
char[] pass = jPasswordField1.getPassword(); 
String passString = new String(pass); 
             if(username.equals("admin") && passString.equals("admin")) 
             { 
                 dispose(); 
                   Home cr1=new Home(); 
 
 
27 
 
                cr1.show(); 
                 
          
             } 
                } 
            }); 
        } 
        catch (Exception ex) { 
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex); 
        } 
    }//GEN-LAST:event_jButton3ActionPerformed 
 
    /** 
     * @param args the command line arguments 
     */ 
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */ 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> 
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. 
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html  
         */ 
        try { 
 
 
28 
 
            for (javax.swing.UIManager.LookAndFeelInfo info : 
javax.swing.UIManager.getInstalledLookAndFeels()) { 
                if ("Nimbus".equals(info.getName())) { 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
                    break; 
                } 
            } 
        } catch (ClassNotFoundException ex) { 
            
java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (InstantiationException ex) { 
            
java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (IllegalAccessException ex) { 
            
java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
            
java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } 
        //</editor-fold> 
 
 
29 
 
        //</editor-fold> 
 
        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() { 
                new Login().setVisible(true); 
            } 
        }); 
    } 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables 
    private javax.swing.JButton jButton3; 
    private javax.swing.JLabel jLabel1; 
    private javax.swing.JLabel jLabel4; 
    private javax.swing.JLabel jLabel8; 
    private javax.swing.JLabel jLabel9; 
    private javax.swing.JPasswordField jPasswordField1; 
    private javax.swing.JTextField jTextField1; 
    // End of variables declaration//GEN-END:variables 
} 
Home.java 
/* 
 * To change this license header, choose License Headers in Project Properties. 
 
 
30 
 
 * To change this template file, choose Tools | Templates 
 * and open the template in the editor. 
 */ 
package networkanomalydetection; 
 
import com.birosoft.liquid.LiquidLookAndFeel; 
 
/** 
 * 
 * @author THILIPAN 
 */ 
public class Home extends javax.swing.JFrame { 
 
    /** 
     * Creates new form Home 
     */ 
    public Home() { 
        initComponents(); 
    } 
 
    /** 
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always 
 
 
31 
 
     * regenerated by the Form Editor. 
     */ 
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN
BEGIN:initComponents 
    private void initComponents() { 
 
        jLabel4 = new javax.swing.JLabel(); 
        jLabel5 = new javax.swing.JLabel(); 
        jLabel1 = new javax.swing.JLabel(); 
        jButton3 = new javax.swing.JButton(); 
        jButton4 = new javax.swing.JButton(); 
        jButton5 = new javax.swing.JButton(); 
        jButton6 = new javax.swing.JButton(); 
        jButton7 = new javax.swing.JButton(); 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout()); 
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N 
        jLabel4.setText("for 5G Network Security"); 
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 
260, 30)); 
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N 
        jLabel5.setText("Network Anomaly Detection based on Domain Adaptation "); 
 
 
32 
 
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 
620, 30)); 
 
        jLabel1.setText("         "); 
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, 340)); 
 
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton3.setText("Load DataSet"); 
        jButton3.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton3ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 
140, 210, 40)); 
 
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton4.setText("Network Anomaly Classifier"); 
        jButton4.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton4ActionPerformed(evt); 
            } 
 
 
33 
 
        }); 
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 
140, 260, 40)); 
 
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton5.setText("Feature Extractor"); 
        jButton5.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton5ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 
220, 210, 40)); 
 
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton6.setText("Performance Evaluation"); 
        jButton6.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton6ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 
220, 260, 40)); 
 
 
34 
 
 
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N 
        jButton7.setText("Log Out"); 
        jButton7.addActionListener(new java.awt.event.ActionListener() { 
            public void actionPerformed(java.awt.event.ActionEvent evt) { 
                jButton7ActionPerformed(evt); 
            } 
        }); 
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 
300, 200, 40)); 
 
        pack(); 
    }// </editor-fold>//GEN-END:initComponents 
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton3ActionPerformed 
        // TODO add your handling code here: 
 
                        LoadDataSet cr1=new LoadDataSet(); 
                        cr1.show(); 
 
         
    }//GEN-LAST:event_jButton3ActionPerformed 
 
 
35 
 
 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton4ActionPerformed 
        // TODO add your handling code here: 
          NetworkAnomalyClassifier cr1=new NetworkAnomalyClassifier(); 
                        cr1.show(); 
         
    }//GEN-LAST:event_jButton4ActionPerformed 
 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton5ActionPerformed 
        // TODO add your handling code here: 
             FeatureExtractor cr1=new FeatureExtractor(); 
                        cr1.show(); 
    }//GEN-LAST:event_jButton5ActionPerformed 
 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton6ActionPerformed 
        // TODO add your handling code here: 
             PerformanceEvaluation cr1=new PerformanceEvaluation(); 
                        cr1.show(); 
    }//GEN-LAST:event_jButton6ActionPerformed 
 
 
 
36 
 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN
FIRST:event_jButton7ActionPerformed 
        // TODO add your handling code here: 
         dispose(); 
                   Login cr1=new Login(); 
                cr1.show(); 
    }//GEN-LAST:event_jButton7ActionPerformed 
 
    /** 
     * @param args the command line arguments 
     */ 
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */ 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> 
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. 
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html  
         */ 
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : 
javax.swing.UIManager.getInstalledLookAndFeels()) { 
                if ("Nimbus".equals(info.getName())) { 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
                    break; 
 
 
37 
 
                } 
            } 
        } catch (ClassNotFoundException ex) { 
            
java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (InstantiationException ex) { 
            
java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (IllegalAccessException ex) { 
            
java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
            
java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE
 , null, ex); 
 
        } 
        //</editor-fold> 
 
        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() { 
 
 
38 
 
                new Home().setVisible(true); 
            } 
        }); 
    } 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables 
    private javax.swing.JButton jButton3; 
    private javax.swing.JButton jButton4; 
    private javax.swing.JButton jButton5; 
    private javax.swing.JButton jButton6; 
    private javax.swing.JButton jButton7; 
    private javax.swing.JLabel jLabel1; 
    private javax.swing.JLabel jLabel4; 
    private javax.swing.JLabel jLabel5; 
    // End of variables declaration//GEN-END:variables 
} 